### ISSUE TITLE
Concatenation.... which dimension ? 

### ISSUE THREAD

**Issue by GabbySuwichaya** [vislearn/ngransac#17]
I got the size of pts1 and pts2 as well as ratios are follows:

```
(Pdb) pts1.shape
(2000, 1, 2)
(Pdb) pts2.shape
(2000, 1, 2)
(Pdb) ratios.shape
(1, 2000, 1)
```
It seems that the ratios have the wrong dimension? 
Can you clarify which dimension I should use? 

```
Traceback (most recent call last):
  File "ngransac_demo.py", line 184, in <module>
    correspondences = np.concatenate((pts1, pts2, ratios), axis=2)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2000 and the array at index 2 has size 1
```

**Comment by ebrach** [comment]
Probably a OpenCV version error. Please see #10
